spring:
  datasource:
    url: jdbc:mysql://localhost:3306/learn_to_jpa?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: hyolim123
    driver-class-name: com.mysql.cj.jdbc.Driver